name: Update Gradle Wrapper

on:
  schedule:
    - cron: '0 4 * * 1' # every week on Mondays at 4:00 UTC
  workflow_dispatch:    # can be run manually from the GitHub UI

jobs:
  update-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@main
        with:
          repo-token: ${{ secrets.PAT_TOKEN_REPO_WORKFLOW_1 }}